"""Typed, presentation-facing contract for the Stage 11 application.

The contract adapts frozen Stage 3--10 artifacts.  It contains no model,
forecast, optimization, tariff, PV, or economics calculations.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Literal

Source = Literal["real"]
TIMEZONE = "Europe/Madrid"
CURRENCY = "EUR"
TARIFF_BANDS_EUR_PER_KWH = (
    (0, 6, 0.18),
    (6, 17, 0.28),
    (17, 22, 0.40),
    (22, 24, 0.28),
)


class Horizon(str, Enum):
    H24 = "24h"
    H72 = "72h"
    H168 = "168h"

    @property
    def hours(self) -> int:
        return int(self.value.removesuffix("h"))


class LoadComponent(str, Enum):
    HVAC = "hvac"
    FRIDGE_FREEZER = "fridge_freezer"
    POOL_CIRCULATION = "pool_circulation"
    POOL_HEATING = "pool_heating"
    SAUNA = "sauna"
    EV1 = "ev1"
    EV2 = "ev2"
    COOKING = "cooking"
    DISHWASHER = "dishwasher"
    WASHER = "washer"
    DRYER = "dryer"
    TV_COMPUTER = "tv_computer"
    LIGHTING_INTERIOR = "lighting_interior"
    LIGHTING_EXTERIOR = "lighting_exterior"
    SMART_HOME_BASE = "smart_home_base"
    PHONE_TABLET = "phone_tablet"


class FlexibilityClass(str, Enum):
    FIXED = "fixed"
    BEHAVIOR_DRIVEN = "behavior_driven"
    LIMITED_FLEXIBILITY = "limited"
    SHIFTABLE = "shiftable"


@dataclass(frozen=True)
class Provenance:
    source: Source
    artifacts: tuple[str, ...]
    meaning: str = (
        "REAL means generated by the frozen project backend, not placeholder "
        "app data; the household itself is a simulated realization."
    )


@dataclass(frozen=True)
class ComponentLoad:
    component: LoadComponent
    kwh: float


@dataclass(frozen=True)
class HistoricalHourPoint:
    timestamp: str
    total_kwh: float
    outdoor_temp_c: float
    indoor_temp_c: float
    occupancy_state: str
    is_away: bool
    components: tuple[ComponentLoad, ...]


@dataclass(frozen=True)
class ForecastHourPoint:
    timestamp: str
    lead_hour: int
    expected_kwh: float
    p10_kwh: float
    p50_kwh: float
    p90_kwh: float
    p95_kwh: float
    outdoor_temp_c: float
    peak_probability: float
    peak_risk_label: str
    tariff_eur_per_kwh: float
    tariff_period: str
    primary_explanation: str
    secondary_explanation: str


@dataclass(frozen=True)
class ForecastBundle:
    horizon: Horizon
    forecast_origin: str
    points: tuple[ForecastHourPoint, ...]
    total_expected_kwh: float
    provenance: Provenance


@dataclass(frozen=True)
class FlexibilityItem:
    component: LoadComponent
    flexibility_class: FlexibilityClass
    notes: str
    earliest_start: str | None
    latest_start: str | None
    latest_completion: str | None
    comfort_band_min: float | None
    comfort_band_max: float | None
    actual_event_count: int
    actual_energy_min_kwh: float | None
    actual_energy_max_kwh: float | None
    actual_duration_min_hours: float | None
    actual_duration_max_hours: float | None


@dataclass(frozen=True)
class ShiftedEvent:
    event_id: str
    component: LoadComponent
    original_start: str
    optimized_start: str
    energy_kwh: float
    duration_hours: float
    shift_hours: float
    constraint_status: str


@dataclass(frozen=True)
class OptimizationHourPoint:
    timestamp: str
    current_load_kwh: float
    optimized_load_kwh: float
    pv_generation_kwh: float
    tariff_eur_per_kwh: float
    current_grid_import_kwh: float
    optimized_grid_import_kwh: float
    current_self_consumed_pv_kwh: float
    optimized_self_consumed_pv_kwh: float
    current_exported_pv_kwh: float
    optimized_exported_pv_kwh: float
    current_net_cost_eur: float
    optimized_net_cost_eur: float


@dataclass(frozen=True)
class OptimizationBundle:
    hourly: tuple[OptimizationHourPoint, ...]
    shifted_events: tuple[ShiftedEvent, ...]
    summary: dict[str, Any]
    provenance: Provenance


@dataclass(frozen=True)
class PVEconomicsRow:
    capacity_kwp: float
    annual_pv_production_kwh: float
    initial_investment_eur: float
    annual_om_eur: float
    current: dict[str, float]
    optimized: dict[str, float]
    optimization_change: dict[str, float]


@dataclass(frozen=True)
class PVBundle:
    rows: tuple[PVEconomicsRow, ...]
    annualization: dict[str, Any]
    effect_decomposition: dict[str, Any]
    provenance: Provenance
    annualized_label: str = "ANNUALIZED ESTIMATE"
    payback_label: str = "SIMPLE PAYBACK"


@dataclass(frozen=True)
class WattWiseData:
    household_label: str
    history: tuple[HistoricalHourPoint, ...]
    history_provenance: Provenance
    forecasts: dict[Horizon, ForecastBundle]
    flexibility: tuple[FlexibilityItem, ...]
    flexibility_provenance: Provenance
    optimization: OptimizationBundle
    pv: PVBundle

    def all_provenance(self) -> tuple[Provenance, ...]:
        return (
            self.history_provenance,
            *(bundle.provenance for bundle in self.forecasts.values()),
            self.flexibility_provenance,
            self.optimization.provenance,
            self.pv.provenance,
        )

    def has_any_mock(self) -> bool:
        return any(provenance.source != "real" for provenance in self.all_provenance())
